version: '3'
services:
  fileserver:
    build: .
    ports:
      - "80:8080"  # Host port 80 mapped to container port 8080
    environment:
      - CONFIG_PATH=/usr/src/app/config.json  # Path inside the container
    volumes:
      - ./files:/files
      - ./config.json:/usr/src/app/config.json